-- 180-49 : séparer les tags YouTube bruts (tags) de la taxonomie éditoriale 180° (taxonomy)
-- 1. Nouvelle colonne taxonomy
ALTER TABLE "Reference" ADD COLUMN IF NOT EXISTS "taxonomy" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

-- 2. Backfill : les slugs appartenant à la taxonomie migrent vers taxonomy,
--    le reste (tags YouTube bruts) reste dans tags. Idempotent : ne retraite
--    que les lignes dont tags contient encore des slugs taxonomie.
UPDATE "Reference" SET
  "taxonomy" = (
    SELECT COALESCE(array_agg(DISTINCT t), '{}')
    FROM unnest("taxonomy" || "tags") AS t
    WHERE t = ANY(ARRAY['cinématique','épuré','dramatique','romantique','luxe','intime','mélancolique','nostalgique','épique','mystérieux','joyeux','poétique','élégant','sombre','énergique','rêveur','brut','sensuel','sérieux','authentique','chaud','froid','teal-orange','désaturé','contrasté','pastel','monochrome','film-grain','vintage','moody-dark','natural-light','high-key','low-key','rose-tinted','vert-forêt','sépia','émotionnel','rythmé','beat-sync','contemplatif','documentaire','voix-off','non-linéaire','flashback','jump-cuts','long-takes','slow-burn','punch-cuts','transitions-créatives','16-9','2.35-scope','2.39-ultra-scope','1.85','open-gate','4-3','1-1-carré','9-16-vertical','6-5','super8-16mm','mariage','corporate','événementiel','publicité-ads','court-métrage','clip-musical','portrait','fashion-lifestyle','sport-action','gastronomie','immobilier','travel-voyage','nature','engagement-couple','sony-fx3','sony-fx6','sony-fx9','sony-a7siii','sony-a1','sony-zve1','canon-c70','canon-c300iii','canon-r5c','bmpcc4k','bmpcc6k','bm-ursa','lumix-s5ii','lumix-s1h','red-komodo','red-monstro','arri-alexa','dji-ronin4d','iphone-smartphone','gopro-action','anamorphique','sphérique','prime','zoom','macro','grand-angle','téléobjectif','vintage-dezoomé','tilt-shift','fisheye','handheld','gimbal-stabilisé','trépied','drone-aérien','fpv','steadicam','slider','jib-grue','sous-marin','caméra-embarquée','timelapse','hyperlapse','slow-motion','double-exposition','360','statique','panoramique','travelling-avant','travelling-arrière','travelling-latéral','push-in','pull-out','rotation','plongée','contre-plongée','dutch-angle','low-angle','high-angle','crane-up','crane-down','zoom-optique','dézoom','plan-large','plan-ensemble','plan-moyen','plan-américain','plan-rapproché','gros-plan','insert-détail','pov-subjectif','over-the-shoulder','two-shot','birds-eye','worms-eye','symétrique','règle-des-tiers','cadre-dans-cadre','leading-lines','silhouette','golden-hour','blue-hour','midi-lumière-dure','nuit-low-light','contre-jour','backlight','studio','softbox','lumière-dure','fenêtre','feu-flamme','néon-led-coloré','practicals','haze-fumée','sous-exposé-intentionnel','intérieur','extérieur','urbain','campagne','montagne','mer-plage','forêt','désert','château-domaine','loft-industriel','église','salle-réception','rooftop','destination-international','jardin','été','automne','hiver','printemps','soleil','nuageux','pluie','neige','brouillard','crépuscule','light-leaks-flares','transitions-morphing','split-screen','texte-titrage','vfx-léger','color-grading-prononcé','lut-cinéma','letterbox-animé','glitch','slow-ramp','solo','duo','groupe-moins-10','groupe-plus-10','foule','sans-sujet-humain','solo-one-man-band','petite-équipe-2-3','équipe-complète','production-cinéma'])
  ),
  "tags" = (
    SELECT COALESCE(array_agg(t), '{}')
    FROM unnest("tags") AS t
    WHERE NOT (t = ANY(ARRAY['cinématique','épuré','dramatique','romantique','luxe','intime','mélancolique','nostalgique','épique','mystérieux','joyeux','poétique','élégant','sombre','énergique','rêveur','brut','sensuel','sérieux','authentique','chaud','froid','teal-orange','désaturé','contrasté','pastel','monochrome','film-grain','vintage','moody-dark','natural-light','high-key','low-key','rose-tinted','vert-forêt','sépia','émotionnel','rythmé','beat-sync','contemplatif','documentaire','voix-off','non-linéaire','flashback','jump-cuts','long-takes','slow-burn','punch-cuts','transitions-créatives','16-9','2.35-scope','2.39-ultra-scope','1.85','open-gate','4-3','1-1-carré','9-16-vertical','6-5','super8-16mm','mariage','corporate','événementiel','publicité-ads','court-métrage','clip-musical','portrait','fashion-lifestyle','sport-action','gastronomie','immobilier','travel-voyage','nature','engagement-couple','sony-fx3','sony-fx6','sony-fx9','sony-a7siii','sony-a1','sony-zve1','canon-c70','canon-c300iii','canon-r5c','bmpcc4k','bmpcc6k','bm-ursa','lumix-s5ii','lumix-s1h','red-komodo','red-monstro','arri-alexa','dji-ronin4d','iphone-smartphone','gopro-action','anamorphique','sphérique','prime','zoom','macro','grand-angle','téléobjectif','vintage-dezoomé','tilt-shift','fisheye','handheld','gimbal-stabilisé','trépied','drone-aérien','fpv','steadicam','slider','jib-grue','sous-marin','caméra-embarquée','timelapse','hyperlapse','slow-motion','double-exposition','360','statique','panoramique','travelling-avant','travelling-arrière','travelling-latéral','push-in','pull-out','rotation','plongée','contre-plongée','dutch-angle','low-angle','high-angle','crane-up','crane-down','zoom-optique','dézoom','plan-large','plan-ensemble','plan-moyen','plan-américain','plan-rapproché','gros-plan','insert-détail','pov-subjectif','over-the-shoulder','two-shot','birds-eye','worms-eye','symétrique','règle-des-tiers','cadre-dans-cadre','leading-lines','silhouette','golden-hour','blue-hour','midi-lumière-dure','nuit-low-light','contre-jour','backlight','studio','softbox','lumière-dure','fenêtre','feu-flamme','néon-led-coloré','practicals','haze-fumée','sous-exposé-intentionnel','intérieur','extérieur','urbain','campagne','montagne','mer-plage','forêt','désert','château-domaine','loft-industriel','église','salle-réception','rooftop','destination-international','jardin','été','automne','hiver','printemps','soleil','nuageux','pluie','neige','brouillard','crépuscule','light-leaks-flares','transitions-morphing','split-screen','texte-titrage','vfx-léger','color-grading-prononcé','lut-cinéma','letterbox-animé','glitch','slow-ramp','solo','duo','groupe-moins-10','groupe-plus-10','foule','sans-sujet-humain','solo-one-man-band','petite-équipe-2-3','équipe-complète','production-cinéma']))
  )
WHERE "tags" && ARRAY['cinématique','épuré','dramatique','romantique','luxe','intime','mélancolique','nostalgique','épique','mystérieux','joyeux','poétique','élégant','sombre','énergique','rêveur','brut','sensuel','sérieux','authentique','chaud','froid','teal-orange','désaturé','contrasté','pastel','monochrome','film-grain','vintage','moody-dark','natural-light','high-key','low-key','rose-tinted','vert-forêt','sépia','émotionnel','rythmé','beat-sync','contemplatif','documentaire','voix-off','non-linéaire','flashback','jump-cuts','long-takes','slow-burn','punch-cuts','transitions-créatives','16-9','2.35-scope','2.39-ultra-scope','1.85','open-gate','4-3','1-1-carré','9-16-vertical','6-5','super8-16mm','mariage','corporate','événementiel','publicité-ads','court-métrage','clip-musical','portrait','fashion-lifestyle','sport-action','gastronomie','immobilier','travel-voyage','nature','engagement-couple','sony-fx3','sony-fx6','sony-fx9','sony-a7siii','sony-a1','sony-zve1','canon-c70','canon-c300iii','canon-r5c','bmpcc4k','bmpcc6k','bm-ursa','lumix-s5ii','lumix-s1h','red-komodo','red-monstro','arri-alexa','dji-ronin4d','iphone-smartphone','gopro-action','anamorphique','sphérique','prime','zoom','macro','grand-angle','téléobjectif','vintage-dezoomé','tilt-shift','fisheye','handheld','gimbal-stabilisé','trépied','drone-aérien','fpv','steadicam','slider','jib-grue','sous-marin','caméra-embarquée','timelapse','hyperlapse','slow-motion','double-exposition','360','statique','panoramique','travelling-avant','travelling-arrière','travelling-latéral','push-in','pull-out','rotation','plongée','contre-plongée','dutch-angle','low-angle','high-angle','crane-up','crane-down','zoom-optique','dézoom','plan-large','plan-ensemble','plan-moyen','plan-américain','plan-rapproché','gros-plan','insert-détail','pov-subjectif','over-the-shoulder','two-shot','birds-eye','worms-eye','symétrique','règle-des-tiers','cadre-dans-cadre','leading-lines','silhouette','golden-hour','blue-hour','midi-lumière-dure','nuit-low-light','contre-jour','backlight','studio','softbox','lumière-dure','fenêtre','feu-flamme','néon-led-coloré','practicals','haze-fumée','sous-exposé-intentionnel','intérieur','extérieur','urbain','campagne','montagne','mer-plage','forêt','désert','château-domaine','loft-industriel','église','salle-réception','rooftop','destination-international','jardin','été','automne','hiver','printemps','soleil','nuageux','pluie','neige','brouillard','crépuscule','light-leaks-flares','transitions-morphing','split-screen','texte-titrage','vfx-léger','color-grading-prononcé','lut-cinéma','letterbox-animé','glitch','slow-ramp','solo','duo','groupe-moins-10','groupe-plus-10','foule','sans-sujet-humain','solo-one-man-band','petite-équipe-2-3','équipe-complète','production-cinéma'];
